In [7]:
import numpy as np

In [48]:
v_arreglo = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
v_arreglo.dtype

dtype('int64')

In [29]:
v_arreglo = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='float64')
v_arreglo.dtype

dtype('float64')

In [34]:
v_arreglo = v_arreglo.astype(np.float64)
v_arreglo

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [35]:
v_arreglo2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
v_arreglo2 = v_arreglo2.astype(np.bool_)
v_arreglo2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [36]:
v_arreglo3 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
v_arreglo3 = v_arreglo3.astype(np.string_)
v_arreglo3

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10'],
      dtype='|S21')

In [46]:
v_arreglo3 = np.array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])
v_arreglo3 = v_arreglo3.astype(np.int8)
v_arreglo3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)