In [1]:
import numpy as np

In [2]:
v_lista = [1, 2]
v_lista

[1, 2]

In [4]:
v_lista * 2

[1, 2, 1, 2]

In [5]:
v_arreglo = np.arange(0, 10)
v_arreglo2 = v_arreglo.copy()
v_arreglo2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Operaciones

In [6]:
v_arreglo * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
# divide by zero encountered in divide
1 / v_arreglo

/tmp/ipykernel_21646/547715094.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / v_arreglo


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
v_matriz = v_arreglo.reshape(2, 5)
v_matriz

v_matriz2 = v_matriz.copy()
v_matriz + v_matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
#producto punto
np.matmul(v_matriz, v_matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [14]:
#otra manera de realizar el producto punto
v_matriz @ v_matriz2.T

array([[ 30,  80],
       [ 80, 255]])