In [2]:
import numpy as np
lista = [1,2,3,4,5,6,7,8,9,0]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [20]:
#crear un arreglo con la lista creada anteriormente
v_arreglo = np.array(lista)
v_arreglo

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [6]:
#tipo de dato
type(v_arreglo)

numpy.ndarray

In [56]:
#slicing: extraer elementos de una secuencia, el limite no se incluye
#v_arreglo[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
#v_arreglo[pos_inicio:pos_final]
#v_arreglo[4:7]: [5, 6, 7]
#v_arreglo[:5]: [1, 2, 3, 4, 5]
#v_arreglo[5:]: [6, 7, 8, 9, 0]
#v_arreglo[5:5]: []
#v_arreglo[:]: todos los elementos del arreglo
#v_arreglo[::3]: [1, 4, 7, 0]
#v_arreglo[-7]: [4] elemento n del final al comienzo
#v_arreglo[-3:]: [8, 9, 0]: 3 últimos elementos

array([8, 9, 0])

In [12]:
#crear una matriz
v_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
v_matriz = np.array(v_matriz)
v_matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
#sumar 2 elementos específicos del arreglo
#1 + 6
v_arreglo[0] + v_arreglo[5]

7

In [14]:
#primera fila de la matriz
#v_matriz[0]: [1, 2, 3]
v_matriz[0]

array([1, 2, 3])

In [13]:
#elemento [1, 2]: 6 de la matriz
v_matriz[1, 2]

6

In [60]:
#slicing: extraer elementos de una secuencia, el limite no se incluye
#v_matriz=
#[1, 2, 3],
#[4, 5, 6],
#[7, 8, 9]

#v_matriz[1:]: de la fila 1 en adelante
#[4, 5, 6],
#[7, 8, 9]

#v_matriz[1:, 0:2]: de la fila 1 en adelante, y las columnas 0 y 1 (el límite no se incluye)
#[4, 5],
#[7, 8]


array([[4, 5],
       [7, 8]])

In [7]:
#arreglo[n] de ceros
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
#arreglo[n] de unos
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
#matriz[n][m] de ceros
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
#matriz[n][m] de unos
print(np.ones((4,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
#matriz de identidad
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
arreglo_anidado = [[1,2],[3,4],[5,6]]
np.array(arreglo_anidado)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
#generar datos
v_arreglo = np.arange(0, 7) # Sin parametro de distancia
v_arreglo
#[0, 1, 2, 3, 4, 5, 6]

array([0, 1, 2, 3, 4, 5, 6])

In [24]:
v_arreglo = np.arange(0, 10, 2) # con parametro de distancia
v_arreglo
#[0, 2, 4, 6, 8]

array([0, 2, 4, 6, 8])