In [1]:
import numpy as np

In [3]:
v_escalar = np.array(42)
print('v_escalar: ', v_escalar)
v_escalar.ndim

v_escalar:  42


0

In [4]:
v_vector = np.array([1, 2, 3])
print('v_vector: ', v_vector)
v_vector.ndim

v_vctor:  [1 2 3]


1

In [6]:
v_matriz = np.array([[1, 2, 3], [4, 5, 6]])
print('v_matriz: ', v_matriz)
v_matriz.ndim

v_matriz:  [[1 2 3]
 [4 5 6]]


2

In [11]:
v_tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [0, 1, 2]]])
print(v_tensor)
v_tensor.ndim

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]


3

## Agregar o eliminar dimensiones

In [20]:
v_tensor = np.array([1, 2, 3], ndmin=10)
print(v_tensor)
v_tensor.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [22]:
expandir = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expandir)
expandir.ndim

[[1 2 3]]


2

In [27]:
print(v_tensor, v_tensor.ndim)
v_tensor2 = np.squeeze(v_tensor)
print(v_tensor2, v_tensor2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
