In [1]:
import numpy as np

In [3]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
#NumPy tiene el método linspace que genera puntos uniformemente espaciados entre dos números.
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand()

0.06521796389726897

In [19]:
np.random.rand(7)

array([0.38125682, 0.63026911, 0.77616562, 0.91265712, 0.39157005,
       0.90253954, 0.70955793])

In [20]:
np.random.rand(7,4)

array([[0.47053431, 0.25302554, 0.52755632, 0.63530868],
       [0.09046414, 0.8459242 , 0.19974012, 0.27365845],
       [0.97864494, 0.94722284, 0.99510111, 0.1632152 ],
       [0.88672512, 0.32186981, 0.66449185, 0.93268788],
       [0.95755555, 0.61996212, 0.09438029, 0.17602982],
       [0.69842974, 0.40443911, 0.30630033, 0.01650834],
       [0.42104546, 0.40103503, 0.61786669, 0.7243513 ]])

In [27]:
np.random.randint(0, 11)

10

In [29]:
np.random.randint(0, 11, (3, 7))

array([[ 1,  9,  2,  0,  6,  8,  9],
       [10,  7,  9,  9,  3,  2,  9],
       [ 5,  9,  4,  2, 10,  0,  0]])