In [2]:
import numpy as np

In [4]:
v_arreglo = np.random.randint(1, 10, (3,2))
v_arreglo

array([[6, 1],
       [2, 8],
       [8, 3]])

In [10]:
#shape indica las dimensiones del arreglo [#filas][#columnas]
v_arreglo.shape

(3, 2)

In [18]:
#cambia la forma de un arreglo
v_arreglo.reshape(1, 6)
#np.reshape(v_arreglo, (1, 6)) hace lo mismo que la linea de arriba

array([[4, 4, 5, 6, 3, 1]])

In [15]:
v_arreglo.reshape(2, 3)

array([[4, 4, 5],
       [6, 3, 1]])

In [9]:
np.reshape(v_arreglo, (2, 3), 'C')

array([[6, 1, 2],
       [8, 8, 3]])

In [10]:
np.reshape(v_arreglo, (2, 3), 'F')

array([[6, 8, 8],
       [2, 1, 3]])

In [11]:
np.reshape(v_arreglo, (2, 3), 'A')

array([[6, 1, 2],
       [8, 8, 3]])