In [20]:
import numpy as np

In [21]:
v_arreglo = np.random.randint(1, 20, 10)
v_arreglo

array([14,  2,  8,  2,  3, 19,  6, 13, 17,  9])

In [22]:
v_matriz = v_arreglo.reshape(2, 5)
v_matriz

array([[14,  2,  8,  2,  3],
       [19,  6, 13, 17,  9]])

In [23]:
#valor maximo / minimo en un arreglo
v_arreglo.max()
v_arreglo.min()

2

In [25]:
#valor maximo / minimo en una matriz
v_matriz.max()
v_matriz.min()

2

In [26]:
#valor maximo / minimo de cada fila
v_matriz.max(1)
v_matriz.min(1)

array([2, 6])

In [27]:
#valor maximo / minimo de cada columna
v_matriz.max(0)
v_matriz.min(0)

array([14,  2,  8,  2,  3])

In [28]:
#posición del maximo / minimo elemento en un arreglo
v_arreglo.argmax()
v_arreglo.argmin()

1

In [29]:
#posición del maximo / minimo elemento por columna en una matriz
v_matriz.argmax(0)
v_matriz.argmin(0)

array([0, 0, 0, 0, 0])

In [32]:
#Rango de valores (máximo-mínimo) a lo largo de un eje.
v_arreglo.ptp()

17

In [33]:
#Rango de valores (máximo-mínimo) a lo largo de un eje.
v_matriz.ptp(0)

array([ 5,  4,  5, 15,  6])

In [35]:
np.percentile(v_arreglo, 50)

8.5

In [36]:
v_arreglo.sort()
v_arreglo

array([ 2,  2,  3,  6,  8,  9, 13, 14, 17, 19])

In [37]:
np.median(v_arreglo)

8.5

In [38]:
np.median(v_matriz, 1)

array([ 3., 14.])

In [39]:
np.std(v_arreglo)

5.9

In [41]:
np.var(v_arreglo)

34.81

In [42]:
np.mean(v_arreglo)

9.3

In [50]:
a = np.array([[1, 2], [3, 4]])
b = np.array([4, 6])
b = np.expand_dims(b, axis=0)
res = np.concatenate((a, b), axis=0)
res

array([[1, 2],
       [3, 4],
       [4, 6]])

In [53]:
transpuesta = a.T
#transpuesta = b.T
transpuesta

array([[1, 3],
       [2, 4]])