In [1]:
import numpy as np

In [4]:
v_arreglo = np.arange(0, 11)
v_arreglo
#array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
temp_arreglo = v_arreglo[0:6]
temp_arreglo
#array([0, 1, 2, 3, 4, 5])

temp_arreglo[:] = 0
temp_arreglo
#array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])
#las posiciones de temp_arreglo siguen haciendo referencia a v_arreglo

array([0, 1, 2, 3, 4, 5])

In [12]:
v_arreglo = np.arange(0, 11)
v_arreglo_copia = v_arreglo.copy()
v_arreglo_copia

v_arreglo_copia[:] = 100
v_arreglo_copia
#array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

v_arreglo
#array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])