In [1]:
import numpy as np

In [17]:
v_arreglo = np.linspace(1, 10, 10, dtype='int8')
v_arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [18]:
v_indices_condicion =  v_arreglo > 5
v_indices_condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [19]:
v_arreglo[v_indices_condicion]
v_arreglo[(v_arreglo > 5) & (v_arreglo < 9)]

array([6, 7, 8], dtype=int8)

In [20]:
v_arreglo[v_arreglo > 5] = 99
v_arreglo

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [22]:
v_arreglo[v_arreglo==99]

array([99, 99, 99, 99, 99], dtype=int8)